# Generated by Django 5.0.6 on 2024-06-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
