# Generated by Django 5.0.6 on 2024-07-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_alter_lineapedido_cantidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente')], max_length=10),
        ),
    ]
