# Generated by Django 5.0.6 on 2024-07-01 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0004_alter_userprofile_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lineapedido',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
    ]
