# Generated by Django 5.0.6 on 2024-07-01 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0007_userprofile_direccion_userprofile_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrador'), ('customer', 'Cliente')], default='customer', max_length=10),
        ),
    ]
